//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by HallQueFront.rc
//
#define IDC_BN_NUMZERO                  3
#define IDC_BN_NUMNINE                  4
#define IDC_BN_NUMEIGHT                 5
#define IDC_BN_NUMSEVEN                 6
#define IDC_BN_NUMSIX                   7
#define IDC_BN_NUMONE                   8
#define IDC_BN_NUMTWO                   9
#define IDC_BN_NUMTHREE                 10
#define IDC_BN_NUMFOUR                  11
#define IDC_BN_NUMFIVE                  12
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_PROPEDBUTTON                103
#define IDD_PROPEDTEXT                  105
#define IDD_PROPEDPIC                   106
#define IDD_PROPCONNECTINFO             109
#define IDD_PROPSHOWTIME                110
#define IDD_PROPSHOWQUENUM              111
#define IDD_PROPPRINTTEXT               112
#define IDD_PROPPRINTPIC                113
#define IDD_PROPPRINTSHOWTIME           114
#define IDR_MAINFRAME                   128
#define IDR_HallQueFrontTYPE            129
#define IDR_MENU_MANAGE                 130
#define IDR_MENU_NOMANAGE               131
#define IDR_MENU_EDITDTAILS             132
#define IDI_ICON_LEFT                   135
#define IDI_ICON_RIGHT                  136
#define IDI_ICON_MIDDLE                 137
#define IDI_ICON_WIDTH                  138
#define IDI_ICON_HEIGHT                 139
#define IDI_ICON_SAMESIZE               140
#define IDI_ICON_BOTTOM                 141
#define IDI_ICON_TOP                    142
#define IDI_ICON_VERI                   143
#define IDI_ICON_HORI                   144
#define IDD_QUESETDLG                   146
#define IDD_STAFFSETDLG                 147
#define IDD_SETPRINT_DIALOG             148
#define IDR_MENU_PRINT                  153
#define IDD_WINDOWSETDLG                155
#define IDD_WNDQUEDLG                   156
#define IDD_DLG_CARD                    157
#define IDD_DIALOG_CALLMSGSET           158
#define IDD_DIALOG_SHOWMSGSET           160
#define IDB_BITMAP_CARD                 163
#define IDB_BITMAP_SET                  165
#define IDD_DIALOG_STBSETDLG            166
#define IDB_BITMAP_NOPAGE               167
#define IDB_BITMAP_WAIT                 168
#define IDD_DIALOG_WARING               169
#define IDD_PASSWORD                    170
#define IDB_KEY                         173
#define IDB_BITMAP_KEY                  173
#define IDD_PASSWORDCHANGE              174
#define IDD_DIALOG_WAITING              177
#define IDB_BITMAP_LOGO                 178
#define IDD_DIALOG_JTTSCALLSET          179
#define IDD_DIALOG_PAGE                 180
#define IDI_ICON_PAGE                   181
#define IDD_DIALOG_SHORTMESSAGE         182
#define IDD_DIALOG_MSGSET               183
#define IDB_BITMAP_SENDMSG              185
#define IDD_PROPMSG_JUDGE               186
#define IDR_TIPMENU                     187
#define IDC_ED_BNWIDTH                  1000
#define IDC_ED_BNHEIGHT                 1001
#define IDC_COMBO_TRANS                 1003
#define IDC_BN_TITLEFONT                1005
#define IDC_RAD_RECT                    1010
#define IDC_RAD_ROUNDRECT               1011
#define IDC_RAD_ELLIPSE                 1012
#define IDC_STA_COLOR                   1014
#define IDC_EDIT_TITLE                  1016
#define IDC_BN_TEXTFONT                 1017
#define IDC_ED_TEXTWIDTH                1018
#define IDC_EDIT_TEXTHEIGHT             1019
#define IDC_RA_TEXTLEFT                 1020
#define IDC_RA_TEXTCENTER               1021
#define IDC_RA_TEXTRIGHT                1022
#define IDC_STA_BKCOLOR                 1023
#define IDC_STA_TEXTCOLOR               1024
#define IDC_ED_CONTENT                  1025
#define IDC_COM_ALPHA                   1027
#define IDC_ED_WIDTH                    1028
#define IDC_ED_HEIGHT                   1029
#define IDC_ED_PATH                     1031
#define IDC_BN_CHOOSEPIC                1032
#define IDC_STA_PIC                     1034
#define IDC_LIST_QUENAME                1036
#define IDC_BN_ADDQUEUE                 1037
#define IDC_BN_DELQUEUE                 1038
#define IDC_ED_AMLIMIT                  1039
#define IDC_ED_PMLIMIT                  1040
#define IDC_ED_DAYLIMIT                 1041
#define IDC_ED_QUENAME                  1042
#define IDC_ED_CALLNAME                 1043
#define IDC_ED_QUEID                    1044
#define IDC_ED_FRONTID                  1045
#define IDC_ED_QUENUMSTART              1046
#define IDC_ED_QUENUMEND                1047
#define IDC_ED_WORKSTARTH               1048
#define IDC_ED_QUENUMEND2               1048
#define IDC_ED_QUESERIALID              1048
#define IDC_COM_STBID                   1049
#define IDC_ED_WORKENDH                 1050
#define IDC_LIST_STAFFNAME              1051
#define IDC_ED_WORKSTARTM               1051
#define IDC_BN_ADDSTAFF                 1052
#define IDC_ED_WORKEND2                 1052
#define IDC_ED_WORKENDM                 1052
#define IDC_BN_DELSTAFF                 1053
#define IDC_ED_STAFFNAME                1054
#define IDC_ED_STAFFID                  1055
#define IDC_COM_STAFFGENDER             1056
#define IDC_BN_SETPHOTO                 1057
#define IDC_BN_SELPHOTO                 1057
#define IDC_STATIC_PHOTO                1058
#define IDC_NUM                         1060
#define IDC_WAIT_NUM                    1061
#define IDC_ADD_TEXT                    1062
#define IDC_ADD_PIC                     1063
#define IDC_CLI_NAME                    1064
#define IDC_TYPE                        1065
#define IDC_BN_CLLEV                    1065
#define IDC_QUEUE                       1066
#define IDC_CUR_TIME                    1067
#define IDC_PRINT_RECT                  1068
#define IDC_ED_ROMOTEIP                 1071
#define IDC_ED_ROMOTEPORT               1072
#define IDC_ED_LOCALPORT                1073
#define IDC_ED_ROMOTEPORT2              1073
#define IDC_BUTTON1                     1074
#define IDC_BN_SENDTEST                 1074
#define IDC_BN_FONT                     1074
#define IDC_ADDWND                      1074
#define IDC_BTN_ADDQUE                  1074
#define IDC_BN_OK                       1074
#define IDC_BN_ADDCARD                  1074
#define IDC_BTN_ADDTEXT                 1074
#define IDC_BTN_ADDSTB                  1074
#define IDC_BTN1                        1074
#define IDC_BUTTON_QUENUM               1074
#define IDC_BN_ADDPAGE                  1074
#define IDC_BTN_SETBK                   1074
#define IDC_BUTTON_ADDMSG               1074
#define IDC_BN_CONTENT                  1074
#define IDC_DELWND                      1075
#define IDC_BTN_DELQUE                  1075
#define IDC_BN_CANCEL                   1075
#define IDC_BN_CANCLE                   1075
#define IDC_BN_DELCARD                  1075
#define IDC_BTN_DELSTB                  1075
#define IDC_BTN6                        1075
#define IDC_BUTTON_WNDNAME              1075
#define IDC_BN_DELPAGE                  1075
#define IDC_BUTTON_DELMSG               1075
#define IDC_BN_ADDMSG                   1075
#define IDC_EDIT_EXAMPLE                1076
#define IDC_BTN2                        1076
#define IDC_BUTTON_QUENUMENG            1076
#define IDC_BN_CONTENT3                 1076
#define IDC_BN_DELMSG                   1076
#define IDC_COM_TIMESTYLE               1077
#define IDC_BTN7                        1077
#define IDC_BUTTON_WNDNAMEENG           1077
#define IDC_BTN3                        1078
#define IDC_COM_QUE                     1079
#define IDC_BTN8                        1079
#define IDC_COMBO_LOGSTAFF              1080
#define IDC_COM_CALLER                  1080
#define IDC_COM_ATTCHQUE                1080
#define IDC_BTN4                        1080
#define IDC_COMBO2                      1081
#define IDC_COM_READCARD                1081
#define IDC_COM_SFZATTCHQUE             1081
#define IDC_BTN9                        1081
#define IDC_ED_PRTEXT                   1082
#define IDC_BTN5                        1082
#define IDC_BTN0                        1083
#define IDC_ED_PRWIDTH                  1084
#define IDC_BTNBK                       1084
#define IDC_ED_PRHEIGHT                 1085
#define IDC_STA_PRTEXTCOLOR             1089
#define IDC_BN_PRTEXTFONT               1090
#define IDC_EDPR_PICWID                 1091
#define IDC_EDPR_PICHEI                 1092
#define IDC_EDPR_PICPATH                1093
#define IDC_BNPR_CHOOSEPIC              1094
#define IDC_COMPR_TIMESTYLE             1095
#define IDC_EDPR_EXAMPLE                1096
#define IDC_BNPR_FONT                   1097
#define IDC_STAPR_COLOR                 1098
#define IDC_WNDLIST                     1099
#define IDC_EDIT_WNDNAME                1100
#define IDC_EDIT_WNDCALLNAME            1101
#define IDC_EDIT_CALLID                 1102
#define IDC_EDIT_EVAID                  1103
#define IDC_EDIT_WNDSCRID               1104
#define IDC_BUTTON3                     1105
#define IDC_BTN_CALLSOUND               1105
#define IDC_BTN_DELETEMSG               1105
#define IDC_BUTTON_ADD                  1105
#define IDC_BN_FLUSHORG                 1105
#define IDC_BUTTON5                     1106
#define IDC_BTN_CALLSHOW                1106
#define IDC_BTN_CHANGEMSG               1106
#define IDC_BUTTON_MVUP                 1106
#define IDC_BUTTON_MSGSET               1106
#define IDC_EDIT_COMSCRID               1107
#define IDC_BTN_MOVEDOWN                1107
#define IDC_BUTTON_MVDOWN               1107
#define IDC_BUTTON4                     1108
#define IDC_BTN_WAITSOUND               1108
#define IDC_BTN_MOVEUP                  1108
#define IDC_BUTTON_DEL                  1108
#define IDC_BN_TESTINTERNET             1108
#define IDC_BUTTON6                     1109
#define IDC_BTN_WAITSHOW                1109
#define IDC_EDIT_CALLID2                1110
#define IDC_EDIT_LEDIPID                1110
#define IDC_EDIT_CALLID3                1111
#define IDC_EDIT_LEDPHYID               1111
#define IDC_EDIT_WNDID                  1112
#define IDC_AUTOLOGIN                   1113
#define IDC_EDIT_ADMSG                  1114
#define IDC_BTN_CHOOSEQUE               1115
#define IDC_LIST_UNDSTQUE               1116
#define IDC_EDIT_SHOWTIME               1116
#define IDC_LIST_ABLEQUE                1117
#define IDC_STATIC_ABLEQUE              1117
#define IDC_BN_WNDOK                    1118
#define IDC_BUTTON7                     1119
#define IDC_BN_WNDCANCEL                1119
#define IDC_LIST1                       1119
#define IDC_LISTBOX_CARD                1119
#define IDC_LIST_SOUNDMSG               1119
#define IDC_LIST_STB                    1119
#define IDC_LIST_LIB                    1119
#define IDC_LIST_PAGE                   1119
#define IDC_LIST_MSG                    1119
#define IDC_LIST_CONTENT                1119
#define IDC_ED_CARDTYPENAME             1120
#define IDC_EDIT_EVALTIMEOUT            1120
#define IDC_LIST_SOUNDMSG2              1120
#define IDC_LIST_SOUND                  1120
#define IDC_ED_CARDID                   1121
#define IDC_ED_CONFIG1                  1122
#define IDC_ED_POSTION1                 1123
#define IDC_ED_CONFIG2                  1124
#define IDC_ED_POSTION2                 1125
#define IDC_ED_CONFIG3                  1126
#define IDC_ED_POSTION3                 1127
#define IDC_CHECK_CONNECT               1128
#define IDC_ED_CONFIG4                  1129
#define IDC_EDIT_TEXT_ADD               1129
#define IDC_ED_POSTION4                 1130
#define IDC_BTN_QUENUM                  1130
#define IDC_ED_SERVERIP                 1131
#define IDC_BTN_STAFFNAME               1131
#define IDC_ED_SERVERPORT               1132
#define IDC_BTN_WNDNAME                 1132
#define IDC_ED_SERVERTIME               1133
#define IDC_LIST_SHOWMSG                1133
#define IDC_BTN_QUENUM2                 1133
#define IDC_BTN_QUENUMENG               1133
#define IDC_COMBO_SHOWCOLOR             1134
#define IDC_BTN_STAFFNAME2              1134
#define IDC_BTN_WNDNAME2                1135
#define IDC_BTN_WNDNAMEENG              1135
#define IDC_CHECK1                      1138
#define IDC_CHECK_CLOSECMP              1138
#define IDC_CHECK_MKALL                 1138
#define IDC_CHECK_MKSDALL               1138
#define IDC_CHECK_MKJTTSALL             1138
#define IDC_CHECK_MKSHALL               1138
#define IDC_CHECK_OPENSHORTMSG          1138
#define IDC_DATETIMEPICKER2             1139
#define IDC_DATE_CLOSE                  1139
#define IDC_CHECK2                      1140
#define IDC_CHECK_CLEARDATA             1140
#define IDC_DATETIMEPICKER3             1141
#define IDC_DATE_CLEARDATA              1141
#define IDC_CHECK3                      1142
#define IDC_CHECK_LACKPAPER             1142
#define IDC_RADIO1                      1143
#define IDC_RA_EXQUE                    1143
#define IDC_RADIO_COMCHN                1143
#define IDC_RAD_COMCHN                  1143
#define IDC_RAD_SHOWCHN                 1143
#define IDC_RADIO2                      1144
#define IDC_RA_EXWINDOW                 1144
#define IDC_RADIO_ENGLISH               1144
#define IDC_RAD_ENGLISH                 1144
#define IDC_RAD_SHOWENG                 1144
#define IDC_TIMESTART                   1145
#define IDC_CHECK_SEND                  1145
#define IDC_TIMEEND                     1148
#define IDC_ED_VOICETIMES               1149
#define IDC_ED_ORGANNAME                1150
#define IDC_ED_ORGANID                  1151
#define IDC_LIST_LEVEL                  1151
#define IDC_BN_ADDLEV                   1152
#define IDC_BN_DELLEV                   1153
#define IDC_ED_LEVELNAME                1154
#define IDC_ED_TOLEVEL                  1155
#define IDC_COM_LEVTOQUEID              1156
#define IDC_STA_CARDPIC                 1157
#define IDC_STA_TIME                    1158
#define IDC_BTN_UP                      1159
#define IDC_BUTTON8                     1160
#define IDC_BTN_DOWN                    1160
#define IDC_EDIT_STBID                  1160
#define IDC_EDIT_STBNAME                1161
#define IDC_EDIT_STBIP                  1162
#define IDC_EDIT_STBPORT                1163
#define IDC_EDIT_SHOWMSG                1164
#define IDC_STA_SHOWPIC                 1165
#define IDC_EDIT_PASSWORD               1166
#define IDC_STATIC_KEY                  1167
#define IDC_BUTTON_SETPSWD              1168
#define IDC_EDIT_OLDPSWD                1172
#define IDC_EDIT_NEWPSWD                1173
#define IDC_STATIC_KEY2                 1174
#define IDC_STA_SHOWWAITPIC             1176
#define IDC_EDIT_                       1177
#define IDC_EDIT_LEDPIPE                1177
#define IDC_SLID_SPEED                  1178
#define IDC_CHECK_USEJTTS               1179
#define IDC_BTN_BUSNAME                 1182
#define IDC_BUTTON_BUSNAME              1183
#define IDC_RADIO_TYPE1                 1187
#define IDC_RADIO_                      1188
#define IDC_RADIO_TYPE2                 1188
#define IDC_BN_TIMEHIDE                 1188
#define IDC_BUTTON2                     1190
#define IDC_BTN_CLRBK                   1190
#define IDC_BN_SAVECON                  1190
#define IDC_CANCELAUTOLOGIN             1190
#define IDC_STA_BTNBK                   1191
#define IDC_CHECK4                      1192
#define IDC_COMBO3                      1194
#define IDC_COM_PARENTORG               1194
#define IDC_EDIT_CELLPHONE              1195
#define IDC_EDIT_QUENUM                 1196
#define IDC_COMBO_MSG                   1197
#define IDC_EDIT_WAITNUM                1198
#define IDC_STATIC_CELLPHONE            1199
#define IDC_STATIC_QUENUM               1200
#define IDC_STATIC_WAITNUM              1201
#define IDC_STATIC_MSG                  1202
#define IDC_EDIT_MSG                    1203
#define IDC_COMBO1                      1206
#define IDC_EDIT_PHONENUM               1208
#define IDC_ED_INTERIP                  1209
#define IDC_ED_INTERPORT                1210
#define IDC_CHECK5                      1212
#define IDC_CHECK_INTER                 1212
#define ID_32771                        32771
#define ID_32772                        32772
#define ID_32773                        32773
#define ID_32774                        32774
#define ID_32775                        32775
#define ID_ADD_BUTTON                   32776
#define ID_ADDBUTTON                    32777
#define ID_ADDTEXT                      32778
#define ID_ADDPIC                       32779
#define ID_MANAGE                       32780
#define ID_QUITMANAGE                   32781
#define ID_32782                        32782
#define ID_QUITHALLQUE                  32783
#define ID_32784                        32784
#define ID_32785                        32785
#define ID_QUITSYS                      32786
#define ID_32787                        32787
#define ID_ERASEBACKPIC                 32788
#define ID_32789                        32789
#define ID_SYSSETING                    32790
#define ID_32791                        32791
#define ID_32792                        32792
#define ID_32793                        32793
#define ID_EDIT                         32794
#define ID_                             32795
#define ID_LINK                         32796
#define ID_DELETE                       32797
#define ID_EDITCTR                      32798
#define ID_LINKCTR                      32799
#define ID_DELETECTR                    32800
#define ID_SHOWTIME                     32801
#define ID_Menu                         32802
#define ID_SHOW_QUENUM                  32803
#define ID_SHOW_TIME                    32804
#define ID_32805                        32805
#define ID_32806                        32806
#define ID_PRINT_EDIT                   32807
#define ID_PRINT_DELETE                 32808
#define ID_32809                        32809
#define ID_32810                        32810
#define ID_32811                        32811
#define ID_Menu32812                    32812
#define ID_QUESET                       32813
#define ID_STAFFSET                     32814
#define ID_WINDOWSET                    32815
#define ID_PRINTSET                     32816
#define ID_32817                        32817
#define ID_CARDSET                      32818
#define ID_32819                        32819
#define ID_COMPREHSET                   32820
#define ID_32821                        32821
#define ID_STBSET                       32822
#define ID_32823                        32823
#define ID_VIEWMINSIZE                  32824
#define ID_32825                        32825
#define ID_LEADINWAV                    32826
#define ID_TIP_32827                    32827
#define ID_TIP_32828                    32828
#define ID_TIP_SHOW                     32829
#define ID_TIP_EXIT                     32830
#define ID_32831                        32831
#define ID_HIDEMAIN                     32832

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        188
#define _APS_NEXT_COMMAND_VALUE         32833
#define _APS_NEXT_CONTROL_VALUE         1213
#define _APS_NEXT_SYMED_VALUE           117
#endif
#endif
